export interface CityData {
  slug: string;
  name: string;
  state: string;
  ecosystem: string;
  hiringDifficulty: string;
  techScene: string;
  avgSalary: string;
  topSectors: string[];
}

export const cities: CityData[] = [
  {
    slug: "san-francisco",
    name: "San Francisco",
    state: "CA",
    ecosystem: "Silicon Valley epicenter — dense VC activity, highest engineer concentration in the US",
    hiringDifficulty: "Extreme. Competition from FAANG, unicorns, and well-funded Series B+ companies drives 12–18 month hiring cycles for senior roles.",
    techScene: "The world's most competitive engineering talent market. Every major AI lab, cloud provider, and fintech challenger competes here.",
    avgSalary: "$180k–$240k for senior engineers",
    topSectors: ["AI/ML", "Fintech", "Web3", "SaaS", "Infrastructure"],
  },
  {
    slug: "new-york",
    name: "New York",
    state: "NY",
    ecosystem: "The US's second-largest tech hub — strong in fintech, adtech, and enterprise SaaS",
    hiringDifficulty: "Very high. Competing with Wall Street compensation packages and a dense startup ecosystem.",
    techScene: "Fintech, media tech, and enterprise software dominate. NYC engineers move fast and expect competitive equity.",
    avgSalary: "$160k–$220k for senior engineers",
    topSectors: ["Fintech", "AdTech", "Enterprise SaaS", "Media", "Healthcare Tech"],
  },
  {
    slug: "austin",
    name: "Austin",
    state: "TX",
    ecosystem: "Fastest-growing US tech hub — Tesla, Apple, and Oracle relocations transformed the market",
    hiringDifficulty: "High and accelerating. Rapid population growth has outpaced talent supply.",
    techScene: "A magnet for engineers leaving California's cost-of-living pressures. Strong in SaaS, semiconductors, and hardware.",
    avgSalary: "$140k–$190k for senior engineers",
    topSectors: ["SaaS", "Semiconductors", "Hardware", "Fintech", "Clean Tech"],
  },
  {
    slug: "miami",
    name: "Miami",
    state: "FL",
    ecosystem: "Emerging Latin American tech gateway — rapidly attracting crypto, fintech, and remote-first companies",
    hiringDifficulty: "Moderate to high. Growing faster than the local talent pool can fill.",
    techScene: "Web3, fintech, and Latin American market plays. Miami offers cost advantages over NYC/SF with strong access to international talent.",
    avgSalary: "$120k–$170k for senior engineers",
    topSectors: ["Web3/Crypto", "Fintech", "LatAm SaaS", "Real Estate Tech", "HealthTech"],
  },
  {
    slug: "seattle",
    name: "Seattle",
    state: "WA",
    ecosystem: "AWS, Microsoft, and a generation of ex-FAANG founders define the talent landscape",
    hiringDifficulty: "Very high. Amazon and Microsoft set compensation benchmarks that make competing expensive.",
    techScene: "Cloud-native engineering culture. Deep expertise in distributed systems, developer tools, and enterprise infrastructure.",
    avgSalary: "$170k–$230k for senior engineers",
    topSectors: ["Cloud Infrastructure", "Developer Tools", "E-commerce", "AI/ML", "Gaming"],
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    state: "CA",
    ecosystem: "Media tech, creator economy, and a growing B2B SaaS corridor in Santa Monica",
    hiringDifficulty: "High. Strong competition from entertainment tech and a dispersed talent pool.",
    techScene: "Creator platforms, streaming tech, and consumer apps dominate. LA's engineering culture blends product intuition with technical depth.",
    avgSalary: "$150k–$210k for senior engineers",
    topSectors: ["Media Tech", "Creator Economy", "E-commerce", "HealthTech", "B2B SaaS"],
  },
  {
    slug: "boston",
    name: "Boston",
    state: "MA",
    ecosystem: "MIT and Harvard pipelines feed one of the US's strongest deep-tech ecosystems",
    hiringDifficulty: "High. Life sciences and biotech compete aggressively for engineering talent.",
    techScene: "Deep-tech, biotech software, and enterprise SaaS are dominant. Boston engineers skew toward research-intensive, technically complex roles.",
    avgSalary: "$150k–$200k for senior engineers",
    topSectors: ["BioTech SaaS", "Deep Tech", "HealthTech", "Enterprise SaaS", "Cybersecurity"],
  },
  {
    slug: "chicago",
    name: "Chicago",
    state: "IL",
    ecosystem: "Midwest's largest tech hub — fintech, proptech, and enterprise software",
    hiringDifficulty: "Moderate to high. Lower cost than coasts but growing quickly.",
    techScene: "Chicago's engineering market centers on fintech, trading systems, and enterprise software. Strong DevOps and backend culture.",
    avgSalary: "$130k–$180k for senior engineers",
    topSectors: ["Fintech", "PropTech", "Enterprise SaaS", "HealthTech", "Trading Tech"],
  },
  {
    slug: "denver",
    name: "Denver",
    state: "CO",
    ecosystem: "Colorado's tech scene grew substantially post-2020 with remote-first migration",
    hiringDifficulty: "Moderate. Growing talent pool, but demand is outpacing supply in senior roles.",
    techScene: "SaaS, cybersecurity, and aerospace tech are strong. Denver engineers value work-life balance alongside technical rigor.",
    avgSalary: "$125k–$170k for senior engineers",
    topSectors: ["Cybersecurity", "SaaS", "Aerospace Tech", "Clean Tech", "HealthTech"],
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    state: "GA",
    ecosystem: "Fastest-growing Southern tech hub — driven by payments, logistics, and enterprise software",
    hiringDifficulty: "Moderate and rising. The payments corridor attracts serious engineering talent.",
    techScene: "Atlanta is the world's payment processing capital. Deep expertise in fintech infrastructure, logistics, and enterprise platforms.",
    avgSalary: "$120k–$165k for senior engineers",
    topSectors: ["Payments/Fintech", "Logistics Tech", "Enterprise SaaS", "HealthTech", "Cybersecurity"],
  },
  {
    slug: "portland",
    name: "Portland",
    state: "OR",
    ecosystem: "Tech extension of the Pacific Northwest — strong open-source culture and developer tooling",
    hiringDifficulty: "Moderate. Smaller market with strong senior talent but limited volume.",
    techScene: "Open-source contributors, developer tools, and sustainability tech. Portland engineers tend toward opinionated, principled technical cultures.",
    avgSalary: "$130k–$175k for senior engineers",
    topSectors: ["Developer Tools", "Open Source SaaS", "Clean Tech", "E-commerce", "HealthTech"],
  },
  {
    slug: "raleigh",
    name: "Raleigh",
    state: "NC",
    ecosystem: "Research Triangle anchors one of the Southeast's strongest engineering pipelines",
    hiringDifficulty: "Moderate. Strong pipeline from NC State, Duke, and UNC keeps supply competitive.",
    techScene: "Enterprise software, cloud infrastructure, and pharma tech dominate. Raleigh is emerging as a serious alternative to coastal markets.",
    avgSalary: "$115k–$160k for senior engineers",
    topSectors: ["Enterprise SaaS", "Pharma Tech", "Cloud Infrastructure", "Cybersecurity", "BioTech"],
  },
  {
    slug: "nashville",
    name: "Nashville",
    state: "TN",
    ecosystem: "Healthcare tech capital of the US — growing B2B SaaS layer on top of a strong enterprise base",
    hiringDifficulty: "Moderate. Healthcare domain expertise commands premiums.",
    techScene: "HealthTech and revenue cycle management dominate. Nashville is developing a broader SaaS corridor beyond healthcare.",
    avgSalary: "$115k–$160k for senior engineers",
    topSectors: ["HealthTech", "Revenue Cycle", "Enterprise SaaS", "Logistics", "Fintech"],
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    state: "AZ",
    ecosystem: "Fast-growing Western hub — semiconductor manufacturing and financial services tech",
    hiringDifficulty: "Moderate. Intel and semiconductor presence sets the engineering standard.",
    techScene: "Semiconductors, financial services software, and logistics tech. Phoenix benefits from lower cost and large university talent pipelines.",
    avgSalary: "$115k–$160k for senior engineers",
    topSectors: ["Semiconductors", "Financial Services Tech", "Logistics", "HealthTech", "SaaS"],
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    state: "MN",
    ecosystem: "Midwest tech hub with strong retail, healthcare, and financial services engineering",
    hiringDifficulty: "Moderate. Legacy enterprise presence competes with startups for talent.",
    techScene: "Healthcare software, retail tech, and financial services platforms. Minneapolis engineers are deeply product-oriented and reliable.",
    avgSalary: "$120k–$165k for senior engineers",
    topSectors: ["HealthTech", "Retail Tech", "Financial Services", "Agri-Tech", "Enterprise SaaS"],
  },
  {
    slug: "san-diego",
    name: "San Diego",
    state: "CA",
    ecosystem: "Defense tech, biotech, and a growing consumer app scene",
    hiringDifficulty: "High. Defense clearances and biotech compete for the same engineering pool.",
    techScene: "Biotech software, defense systems, and wireless technology. San Diego engineers often have specialized domain expertise.",
    avgSalary: "$140k–$195k for senior engineers",
    topSectors: ["BioTech", "Defense Tech", "Wireless/Telecom", "HealthTech", "Consumer Apps"],
  },
  {
    slug: "salt-lake-city",
    name: "Salt Lake City",
    state: "UT",
    ecosystem: "'Silicon Slopes' — Utah's tech corridor rivals established hubs in SaaS density",
    hiringDifficulty: "Moderate. Strong BYU and University of Utah pipeline keeps supply healthy.",
    techScene: "B2B SaaS is the dominant sector. Salt Lake City companies often scale remote-first with a strong in-state engineering core.",
    avgSalary: "$115k–$160k for senior engineers",
    topSectors: ["B2B SaaS", "Fintech", "EdTech", "HealthTech", "E-commerce"],
  },
  {
    slug: "detroit",
    name: "Detroit",
    state: "MI",
    ecosystem: "Automotive tech transformation — legacy OEM investment in software-defined vehicles",
    hiringDifficulty: "Moderate. Automotive domain expertise is highly specialized and valued.",
    techScene: "Mobility tech, embedded systems, and automotive software dominate. Detroit is undergoing a deep technical transformation.",
    avgSalary: "$110k–$155k for senior engineers",
    topSectors: ["Mobility Tech", "Embedded Systems", "Automotive SaaS", "Manufacturing Tech", "SupplyChain"],
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh",
    state: "PA",
    ecosystem: "Robotics and AI research hub anchored by Carnegie Mellon University",
    hiringDifficulty: "Moderate. CMU pipeline feeds world-class AI/robotics talent.",
    techScene: "Robotics, autonomous systems, and applied AI are Pittsburgh's engineering identity. Bridging academia and production engineering is a local specialty.",
    avgSalary: "$120k–$165k for senior engineers",
    topSectors: ["Robotics", "Autonomous Systems", "Applied AI", "HealthTech", "EdTech"],
  },
  {
    slug: "washington-dc",
    name: "Washington DC",
    state: "DC",
    ecosystem: "GovTech and cybersecurity capital — defense, intelligence, and federal contractor engineering",
    hiringDifficulty: "High. Security clearances create significant talent scarcity.",
    techScene: "Federal IT modernization, cybersecurity, and defense software define the market. Commercial tech is growing rapidly in NoVa.",
    avgSalary: "$140k–$195k for senior engineers",
    topSectors: ["GovTech", "Cybersecurity", "Defense Software", "HealthTech", "Enterprise SaaS"],
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getCitySlugs(): string[] {
  return cities.map((c) => c.slug);
}
